AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Auth-messaging

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: java11
    Environment:
      Variables:
        AWS_REGION: us-east-1

Resources:
  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Messages
      AttributeDefinitions:
        - AttributeName: messageId
          AttributeType: S
        - AttributeName: conversationId
          AttributeType: S
        - AttributeName: recipientId
          AttributeType: S
        - AttributeName: senderId
          AttributeType: S
        - AttributeName: content
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: messageId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: ConversationIndex
          KeySchema:
            - AttributeName: conversationId
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: username
          AttributeType: S
        - AttributeName: passwordHash
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: N
        - AttributeName: lastLogin
          AttributeType: N
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: UsernameIndex
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL
  MessageNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: MessageNotificationTopic

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.instant.message.MessageApplication::handleAuthRequest
      CodeUri: build/distributions/instant-messaging-system.zip
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /auth/{proxy+}
            Method: ANY

  MessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.instant.message.MessageApplication::handleAuthRequest
      CodeUri: build/distributions/instant-messaging-system.zip
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt MessageNotificationTopic.TopicName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /messages/{proxy+}
            Method: ANY

  WebSocketFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.instant.message.controller.WebSocketController::handleAuthRequest
      CodeUri: build/distributions/instant-messaging-system.zip
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MessagesTable
      Events:
        WebSocketConnect:
          Type: WebSocket
          Properties:
            Route: $connect
        WebSocketDisconnect:
          Type: WebSocket
          Properties:
            Route: $disconnect
        WebSocketDefault:
          Type: WebSocket
          Properties:
            Route: $default

  NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.example.messaging.MessagingApplication::handleNotification
      CodeUri: build/distributions/instant-messaging-system.zip
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MessagesTable
      Events:
        SnsEvent:
          Type: SNS
          Properties:
            Topic: !GetAtt MessageNotificationTopic.TopicName

Outputs:
  WebSocketApiUrl:
    Description: "WebSocket API URL"
    Value: !GetAtt WebSocketFunction.ApiUrl
  RestApiUrl:
    Description: "REST API URL"
    Value: !GetAtt AuthFunction.ApiUrl